## Attention

In [94]:
import numpy as np
from gensim.models import Word2Vec

In [95]:
np.random.seed(42)
d_model = 4
d_k = 3

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

In [96]:
# Embeddings
sentences = [
    ["cat", "eats", "fish"]
]

model = Word2Vec(
    sentences,
    vector_size=d_model,
    window=2,
    min_count=1,
    workers=1
)

In [97]:
X = np.array([model.wv[word] for word in ["cat", "eats", "fish"]])

print("Input matrix X:")  
print(X)  
print(f"Shape: {X.shape}")  

Input matrix X:
[[-0.1253857  -0.09408429  0.18451262 -0.03833678]
 [-0.23257375 -0.17792022  0.16147181  0.2243247 ]
 [-0.01340568  0.00591078  0.12758374  0.22523183]]
Shape: (3, 4)


In [98]:
Wq = np.random.randn(d_model, d_k) * 0.1  
Wk = np.random.randn(d_model, d_k) * 0.1  
Wv = np.random.randn(d_model, d_k) * 0.1

print(f"Wq Shape: {Wq.shape}")  
print(f"Wk Shape: {Wk.shape}")  
print(f"Wv Shape: {Wv.shape}")  

Wq Shape: (4, 3)
Wk Shape: (4, 3)
Wv Shape: (4, 3)


In [99]:
# Create Query matrix  
Q = np.dot(X, Wq)  
print("Query matrix Q:")  
print(Q)  
print(f"Shape: {Q.shape}")  

Query matrix Q:
[[ 0.00650106  0.01987339 -0.01279516]
 [-0.00097925  0.00937803 -0.02892592]
 [ 0.03260272 -0.00059947 -0.01748611]]
Shape: (3, 3)


In [100]:
# Create Key matrix  
K = np.dot(X, Wk)  
print("Keys matrix K:")  
print(K)  
print(f"Shape: {K.shape}")  

Keys matrix K:
[[-0.01363225  0.00720128  0.05117652]
 [-0.01534992  0.04122829  0.02623144]
 [-0.01732683 -0.01453153 -0.01089245]]
Shape: (3, 3)


In [101]:
# Create Value matrix  
V = np.dot(X, Wv)  
print("Value matrix K:")  
print(V)  
print(f"Shape: {V.shape}")  

Value matrix K:
[[-0.00375627  0.03528375  0.02160747]
 [-0.02746645  0.05646759  0.00435443]
 [-0.03054797  0.04165466 -0.02629892]]
Shape: (3, 3)


In [102]:
# Attention scores
scaled_scores = Q @ K.T / np.sqrt(d_k)
attention_weights = softmax(scaled_scores)

# Apply to values
output = attention_weights @ V

print("Scores:")
print(scores)

print("scaled_scores:")
print(scaled_scores)

print("attention_weights:")
print(attention_weights)

print("output:")
print(output)

Scores:
[[-0.00060032  0.00038392 -0.00026206]
 [-0.00139944 -0.0003571   0.00019576]
 [-0.00134364 -0.00098385 -0.00036572]]
scaled_scores:
[[-0.0003466   0.00022166 -0.0001513 ]
 [-0.00080797 -0.00020617  0.00011302]
 [-0.00077575 -0.00056803 -0.00021115]]
attention_weights:
[[0.3332485  0.33343792 0.33331358]
 [0.33316415 0.33336471 0.33347114]
 [0.33324752 0.33331675 0.33343573]]
output:
[[-0.02059218  0.04447076 -0.0001132 ]
 [-0.02059466  0.04447021 -0.00011948]
 [-0.02059258  0.04446897 -0.00011696]]
