In [2]:
import torch
import torch.nn as nn
import math

In [5]:
#1. vocabulary
vocab = {
    "<pad>": 0,
    "dog": 1,
    "chasing": 2,
    "cat": 3     
}

sentence1 = ["dog","chasing", "cat"]
sentence2 = ["cat", "chasing", "dog"]

def tokenize(sentence):
    return torch.tensor([vocab[word] for word in sentence])

    
tokens1 = tokenize(sentence1)
tokens2 = tokenize(sentence2)

print(tokens1)
print(tokens2)

tensor([1, 2, 3])
tensor([3, 2, 1])


In [7]:
# 2 Word Embedding Layer


embedding = nn.Embedding(
    num_embeddings = len(vocab),
    embedding_dim = 4
)

word_embeddings1 = embedding(tokens1)
word_embeddings2 = embedding(tokens2)


print("\nWord embeddings1")
print(word_embeddings1)

print("\nWord embeddings2")
print(word_embeddings2)


Word embeddings1
tensor([[ 0.8943,  0.8612, -0.8565, -2.0031],
        [ 0.2324,  0.2625, -0.7104,  0.3343],
        [ 0.2429,  1.3912, -0.1646, -0.8609]], grad_fn=<EmbeddingBackward0>)

Word embeddings2
tensor([[ 0.2429,  1.3912, -0.1646, -0.8609],
        [ 0.2324,  0.2625, -0.7104,  0.3343],
        [ 0.8943,  0.8612, -0.8565, -2.0031]], grad_fn=<EmbeddingBackward0>)
