In [7]:
import torch
import torch.nn as nn
import math

In [8]:
#1. vocabulary
vocab = {
    "<pad>": 0,
    "dog": 1,
    "chasing": 2,
    "cat": 3     
}

sentence1 = ["dog","chasing", "cat"]
sentence2 = ["cat",  "chasing", "dog"]

def tokenize(sentence):
    return torch.tensor([vocab[word] for word in sentence])

    
tokens1 = tokenize(sentence1)
tokens2 = tokenize(sentence2)

print(tokens1)
print(tokens2)

tensor([1, 2, 3])
tensor([3, 2, 1])


In [9]:
# 2 Word Embedding Layer
embedding_dim = 4

embedding = nn.Embedding(
    num_embeddings = len(vocab),
    embedding_dim = embedding_dim
)

x1 = embedding(tokens1)
x2 = embedding(tokens2)


print("\nWord embeddings1")
print(x1)

print("\nWord embeddings2")
print(x2)


Word embeddings1
tensor([[ 1.6331, -2.3551,  0.5199, -0.2647],
        [-0.6458,  0.9036, -0.0830, -1.1441],
        [-1.0457, -0.6781,  0.6014, -0.1407]], grad_fn=<EmbeddingBackward0>)

Word embeddings2
tensor([[-1.0457, -0.6781,  0.6014, -0.1407],
        [-0.6458,  0.9036, -0.0830, -1.1441],
        [ 1.6331, -2.3551,  0.5199, -0.2647]], grad_fn=<EmbeddingBackward0>)


In [10]:
Wq = nn.Linear(embedding_dim, embedding_dim, bias=False)
Wk = nn.Linear(embedding_dim, embedding_dim, bias=False)
Wv = nn.Linear(embedding_dim, embedding_dim, bias=False)


def self_attention(x):

    Q = Wq(x)
    K = Wk(x)
    V = Wv(x)

    # Attention scores
    scores = Q @ K.T

    # Normalize
    weights = torch.softmax(scores, dim=-1)

    # Weighted sum
    output = weights @ V

    return output, weights

In [11]:
out1, attn1 = self_attention(x1)
out2, attn2 = self_attention(x2)

print(attn1)

print(attn2)

tensor([[0.4541, 0.1501, 0.3958],
        [0.2943, 0.4125, 0.2932],
        [0.2395, 0.4907, 0.2698]], grad_fn=<SoftmaxBackward0>)
tensor([[0.2698, 0.4907, 0.2395],
        [0.2932, 0.4125, 0.2943],
        [0.3958, 0.1501, 0.4541]], grad_fn=<SoftmaxBackward0>)
