In [1]:
import torch
import torch.nn as nn


In [2]:
text = "hello world"

In [3]:
# -------------------------
# 1. Character vocabulary
# -------------------------
chars = sorted(set(text))

stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}

vocab_size = len(chars)

print(chars)
print("vocab size:", vocab_size)


[' ', 'd', 'e', 'h', 'l', 'o', 'r', 'w']
vocab size: 8


In [6]:

# -------------------------
# 2. Convert text to IDs
# -------------------------
data = torch.tensor([
    stoi[ch] for ch in text
])

print("IDs:")
print(data)

print("\nShape:")
print(data.shape)

IDs:
tensor([3, 2, 4, 4, 5, 0, 7, 5, 6, 4, 1])

Shape:
torch.Size([11])


In [5]:

# -------------------------
# 3. Embedding
# -------------------------
EMBED_DIM = 8

embedding = nn.Embedding(
    vocab_size,
    EMBED_DIM
)

x = data[]

print("\nInput IDs:")
print(x)

vectors = embedding(x)

print("\nEmbedding:")
print(vectors)

print("\nShape:")
print(vectors.shape)


Input IDs:
tensor([3, 2, 4, 4, 5])

Embedding:
tensor([[ 0.8313,  0.2095,  1.2897,  0.4071, -0.3905,  1.5575,  0.1231,  0.7208],
        [-0.2834, -1.1557, -0.1825, -1.6124, -1.3722, -1.0246, -0.7482,  1.3202],
        [ 1.2607,  2.0910, -0.1533, -2.8423, -1.7277, -0.2550, -0.7246, -0.2046],
        [ 1.2607,  2.0910, -0.1533, -2.8423, -1.7277, -0.2550, -0.7246, -0.2046],
        [ 0.8650, -1.7995,  0.9774, -0.9165,  2.0287,  0.0091, -0.7297, -0.8097]],
       grad_fn=<EmbeddingBackward0>)

Shape:
torch.Size([5, 8])
