In [68]:
import numpy as np

In [69]:
Q = np.array([
    [1,  2,  3,  4,  5,  6,  7,  8],
    [9, 10, 11, 12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21, 22, 23, 24]
])

print(Q)
print(Q.shape)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
(3, 8)


In [70]:
seq_len = len(Q)
d_model = 8

num_heads = 4
head_dim = d_model // num_heads

Q = Q.reshape(seq_len, num_heads, head_dim)


print("Q:", Q)
print("Q.shape", Q.shape)

Q: [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
Q.shape (3, 4, 2)


In [71]:
Q = np.transpose(Q, (1,0,2))

print("Q:", Q)
print("Q.shape", Q.shape)

Q: [[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]
Q.shape (4, 3, 2)


In [72]:
for h in range(num_heads):
    q = Q[h]  # Shape: (seq_len, head_dim)
    print("q", q)

q [[ 1  2]
 [ 9 10]
 [17 18]]
q [[ 3  4]
 [11 12]
 [19 20]]
q [[ 5  6]
 [13 14]
 [21 22]]
q [[ 7  8]
 [15 16]
 [23 24]]


In [73]:
heads_output = np.array([
[
 [101,102],
 [103,104],
 [105,106]
],

[
 [201,202],
 [203,204],
 [205,206]
],

[
 [301,302],
 [303,304],
 [305,306]
],

[
 [401,402],
 [403,404],
 [405,406]
]
])

print(heads_output.shape)
print(heads_output)

(4, 3, 2)
[[[101 102]
  [103 104]
  [105 106]]

 [[201 202]
  [203 204]
  [205 206]]

 [[301 302]
  [303 304]
  [305 306]]

 [[401 402]
  [403 404]
  [405 406]]]


In [74]:
concat = np.transpose(heads_output,(1,0,2))
print(concat)
concat = concat.reshape(3,8)
print(concat)

[[[101 102]
  [201 202]
  [301 302]
  [401 402]]

 [[103 104]
  [203 204]
  [303 304]
  [403 404]]

 [[105 106]
  [205 206]
  [305 306]
  [405 406]]]
[[101 102 201 202 301 302 401 402]
 [103 104 203 204 303 304 403 404]
 [105 106 205 206 305 306 405 406]]
