In [1]:
import torch
import torch.nn as nn
import math

In [51]:
#1. vocabulary
vocab = {
    "<pad>": 0,
    "dog": 1,
    "is": 2,
    "chasing": 3,
    "cat": 4     
}

sentence1 = ["dog", "is", "chasing", "cat"]
sentence2 = ["cat", "is", "chasing", "dog"]

def tokenize(sentence):
    return torch.tensor([vocab[word] for word in sentence])

    
tokens1 = tokenize(sentence1)
tokens2 = tokenize(sentence2)

print(tokens1)
print(tokens2)

tensor([1, 2, 3, 4])
tensor([4, 2, 3, 1])


In [52]:
# 2 Word Embedding Layer

embedding_dim = 8

embedding = nn.Embedding(
    num_embeddings = len(vocab),
    embedding_dim = embedding_dim
)

word_embeddings1 = embedding(tokens1)
word_embeddings2 = embedding(tokens2)

print("\nWord embeddings1 shape")
print(word_embeddings1.shape)

print("\nWord embeddings2 shape")
print(word_embeddings2.shape)


print("\nWord embeddings1")
print(word_embeddings1)

print("\nWord embeddings2")
print(word_embeddings2)


Word embeddings1 shape
torch.Size([4, 8])

Word embeddings2 shape
torch.Size([4, 8])

Word embeddings1
tensor([[-0.9305,  0.7196,  0.6291, -1.2950,  1.4816, -0.2925,  0.0358,  0.5073],
        [ 0.7365, -1.5306, -0.5909, -0.7313, -0.3689, -0.2789, -1.5521,  0.0670],
        [-0.4385,  0.3785,  0.4431, -0.6755,  0.1405, -1.7322, -0.4619, -0.2360],
        [ 0.5047,  0.5989,  1.7379,  0.9332,  1.1372, -0.0081,  1.0010,  0.8217]],
       grad_fn=<EmbeddingBackward0>)

Word embeddings2
tensor([[ 0.5047,  0.5989,  1.7379,  0.9332,  1.1372, -0.0081,  1.0010,  0.8217],
        [ 0.7365, -1.5306, -0.5909, -0.7313, -0.3689, -0.2789, -1.5521,  0.0670],
        [-0.4385,  0.3785,  0.4431, -0.6755,  0.1405, -1.7322, -0.4619, -0.2360],
        [-0.9305,  0.7196,  0.6291, -1.2950,  1.4816, -0.2925,  0.0358,  0.5073]],
       grad_fn=<EmbeddingBackward0>)


In [46]:
pe = torch.zeros(10, 8)
position = torch.arange(0, 10).unsqueeze(1)

In [38]:
even_dimesion_indices = torch.arange(0, 8, 2)
decay_factor = -math.log(10000)/8


div_term = even_dimesion_indices * decay_factor
exp_div_term = torch.exp(div_term)
print(div_term, exp_div_term)

tensor([-0.0000, -2.3026, -4.6052, -6.9078]) tensor([1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03])


In [48]:
pe[:, 0::2] = torch.sin(position * exp_div_term)
pe[:, 1::2] = torch.cos(position * exp_div_term)

In [49]:
pe

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01],
        [-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
          9.9875e-01,  5.0000e-03,  9.9999e-01],
        [-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
          9.9820e-01,  6.0000e-03,  9.9998e-01],
        [ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
          9.9755e-01,  6.9999e-03,  9.9998e-01],
        [ 9.8936

In [50]:
pe = pe.unsqueeze(1)
pe

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00]],

        [[ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
           9.9995e-01,  1.0000e-03,  1.0000e+00]],

        [[ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
           9.9980e-01,  2.0000e-03,  1.0000e+00]],

        [[ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
           9.9955e-01,  3.0000e-03,  1.0000e+00]],

        [[-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
           9.9920e-01,  4.0000e-03,  9.9999e-01]],

        [[-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
           9.9875e-01,  5.0000e-03,  9.9999e-01]],

        [[-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
           9.9820e-01,  6.0000e-03,  9.9998e-01]],

        [[ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
           9.9755e-01,  6.9999e-03, 