In [99]:
import torch

In [100]:
B = 3
T = 4
C = 8
H = 2
D = C // H

In [101]:
torch.manual_seed(32)
x = torch.randint(high=99, size=(B, T, C))
print(x)
print("Original:", x.shape)

tensor([[[64, 71, 30, 78, 97, 78, 57, 71],
         [47, 45, 40, 97, 48, 52, 67, 17],
         [32, 35, 69, 71, 74, 70,  9, 82],
         [23, 66, 50, 23, 76, 33, 32, 86]],

        [[ 6,  0, 16, 25, 79, 30, 73, 24],
         [96, 83, 31, 32, 10, 15, 35, 40],
         [96, 28, 89,  3, 81, 39, 70, 59],
         [90,  2, 25, 35, 46, 76, 72, 37]],

        [[59, 29, 15, 59, 62, 32, 20, 42],
         [31, 36, 37, 78, 58, 39,  2, 55],
         [43, 11, 36,  3, 56,  2, 75, 82],
         [31,  8, 76, 70, 36,  9, 19, 52]]])
Original: torch.Size([3, 4, 8])


In [102]:
# Split heads
x = x.view(B, T, H, D)
print("Split:", x.shape) # (3, 4, 2, 4)
print(x)

Split: torch.Size([3, 4, 2, 4])
tensor([[[[64, 71, 30, 78],
          [97, 78, 57, 71]],

         [[47, 45, 40, 97],
          [48, 52, 67, 17]],

         [[32, 35, 69, 71],
          [74, 70,  9, 82]],

         [[23, 66, 50, 23],
          [76, 33, 32, 86]]],


        [[[ 6,  0, 16, 25],
          [79, 30, 73, 24]],

         [[96, 83, 31, 32],
          [10, 15, 35, 40]],

         [[96, 28, 89,  3],
          [81, 39, 70, 59]],

         [[90,  2, 25, 35],
          [46, 76, 72, 37]]],


        [[[59, 29, 15, 59],
          [62, 32, 20, 42]],

         [[31, 36, 37, 78],
          [58, 39,  2, 55]],

         [[43, 11, 36,  3],
          [56,  2, 75, 82]],

         [[31,  8, 76, 70],
          [36,  9, 19, 52]]]])


In [103]:
# Move heads before tokens
x = x.transpose(1, 2) 
print("Attention format:", x.shape) # (3, 2, 4, 4)
print(x)

Attention format: torch.Size([3, 2, 4, 4])
tensor([[[[64, 71, 30, 78],
          [47, 45, 40, 97],
          [32, 35, 69, 71],
          [23, 66, 50, 23]],

         [[97, 78, 57, 71],
          [48, 52, 67, 17],
          [74, 70,  9, 82],
          [76, 33, 32, 86]]],


        [[[ 6,  0, 16, 25],
          [96, 83, 31, 32],
          [96, 28, 89,  3],
          [90,  2, 25, 35]],

         [[79, 30, 73, 24],
          [10, 15, 35, 40],
          [81, 39, 70, 59],
          [46, 76, 72, 37]]],


        [[[59, 29, 15, 59],
          [31, 36, 37, 78],
          [43, 11, 36,  3],
          [31,  8, 76, 70]],

         [[62, 32, 20, 42],
          [58, 39,  2, 55],
          [56,  2, 75, 82],
          [36,  9, 19, 52]]]])


In [104]:
# ---- MERGE HEADS ----

# B H T D -> B T H D
x = x.transpose(1, 2)
print("Before merge:", x.shape)
print(x)

Before merge: torch.Size([3, 4, 2, 4])
tensor([[[[64, 71, 30, 78],
          [97, 78, 57, 71]],

         [[47, 45, 40, 97],
          [48, 52, 67, 17]],

         [[32, 35, 69, 71],
          [74, 70,  9, 82]],

         [[23, 66, 50, 23],
          [76, 33, 32, 86]]],


        [[[ 6,  0, 16, 25],
          [79, 30, 73, 24]],

         [[96, 83, 31, 32],
          [10, 15, 35, 40]],

         [[96, 28, 89,  3],
          [81, 39, 70, 59]],

         [[90,  2, 25, 35],
          [46, 76, 72, 37]]],


        [[[59, 29, 15, 59],
          [62, 32, 20, 42]],

         [[31, 36, 37, 78],
          [58, 39,  2, 55]],

         [[43, 11, 36,  3],
          [56,  2, 75, 82]],

         [[31,  8, 76, 70],
          [36,  9, 19, 52]]]])


In [105]:
# B T H D -> B T C
x = x.reshape(B, T, C)

print("Merged:", x.shape)
print(x)

Merged: torch.Size([3, 4, 8])
tensor([[[64, 71, 30, 78, 97, 78, 57, 71],
         [47, 45, 40, 97, 48, 52, 67, 17],
         [32, 35, 69, 71, 74, 70,  9, 82],
         [23, 66, 50, 23, 76, 33, 32, 86]],

        [[ 6,  0, 16, 25, 79, 30, 73, 24],
         [96, 83, 31, 32, 10, 15, 35, 40],
         [96, 28, 89,  3, 81, 39, 70, 59],
         [90,  2, 25, 35, 46, 76, 72, 37]],

        [[59, 29, 15, 59, 62, 32, 20, 42],
         [31, 36, 37, 78, 58, 39,  2, 55],
         [43, 11, 36,  3, 56,  2, 75, 82],
         [31,  8, 76, 70, 36,  9, 19, 52]]])
