In [1]:
import numpy as np

In [2]:
# 6x6 images
image_o = np.array([
    [0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0],
    [0, 0, 1, 1, 0, 0]
])

image_x = np.array([
    [1,0,0,0,0,1],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [1,0,0,0,0,1]
])


# 3x3 kernel - detects the "/" diagonal
kernel = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
],dtype=int)

bias = -2

kernel

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [3]:
# Convolution and max pooling, written once and reused for both images
def convolve(image, kernel, bias, verbose=True):
    k_h, k_w = kernel.shape
    out_h = image.shape[0] - k_h + 1
    out_w = image.shape[1] - k_w + 1

    feature_map = np.zeros((out_h, out_w), dtype=int)

    for i in range(out_h):
        for j in range(out_w):
            window = image[i:i+k_h, j:j+k_w]

            weighted_sum = np.sum(window * kernel)
            conv_value = weighted_sum + bias

            if verbose:
                print(f"\nWindow ({i},{j})")
                print(window)
                print("Weighted Sum =", weighted_sum)
                print("After Bias =", conv_value)

            feature_map[i, j] = conv_value

    return feature_map


def max_pool(feature_map, pool_size=2, stride=2, verbose=True):
    pool_h = (feature_map.shape[0] - pool_size) // stride + 1
    pool_w = (feature_map.shape[1] - pool_size) // stride + 1

    pooled = np.zeros((pool_h, pool_w), dtype=int)

    for i in range(pool_h):
        for j in range(pool_w):
            r = i * stride
            c = j * stride
            window = feature_map[r:r+pool_size, c:c+pool_size]

            if verbose:
                print(f"\nPool Window ({i},{j})")
                print(window)
                print("Max =", np.max(window))

            pooled[i, j] = np.max(window)

    return pooled

In [4]:
# ----- image_o -----
feature_map_o = convolve(image_o, kernel, bias)

print("\nFeature Map Before ReLU:")
print(feature_map_o)

relu_o = np.maximum(0, feature_map_o)
print("\nFeature Map after ReLU:")
print(relu_o)

max_pool_o = max_pool(relu_o)

print("\nAfter Max Pooling:")
print(max_pool_o)


Window (0,0)
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Weighted Sum = 3
After Bias = 1

Window (0,1)
[[0 1 1]
 [1 0 0]
 [0 0 0]]
Weighted Sum = 1
After Bias = -1

Window (0,2)
[[1 1 0]
 [0 0 1]
 [0 0 0]]
Weighted Sum = 0
After Bias = -2

Window (0,3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Weighted Sum = 1
After Bias = -1

Window (1,0)
[[0 1 0]
 [1 0 0]
 [1 0 0]]
Weighted Sum = 1
After Bias = -1

Window (1,1)
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Weighted Sum = 0
After Bias = -2

Window (1,2)
[[0 0 1]
 [0 0 0]
 [0 0 0]]
Weighted Sum = 1
After Bias = -1

Window (1,3)
[[0 1 0]
 [0 0 1]
 [0 0 1]]
Weighted Sum = 0
After Bias = -2

Window (2,0)
[[1 0 0]
 [1 0 0]
 [0 1 0]]
Weighted Sum = 0
After Bias = -2

Window (2,1)
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Weighted Sum = 1
After Bias = -1

Window (2,2)
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Weighted Sum = 0
After Bias = -2

Window (2,3)
[[0 0 1]
 [0 0 1]
 [0 1 0]]
Weighted Sum = 1
After Bias = -1

Window (3,0)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Weighted Sum = 1
After Bias = -1

Window (3,1)
[[0 0 0]
 [1

In [5]:
# ----- image_x -----
feature_map_x = convolve(image_x, kernel, bias)

print("\nFeature Map Before ReLU:")
print(feature_map_x)

relu_x = np.maximum(0, feature_map_x)
print("\nFeature Map after ReLU:")
print(relu_x)

max_pool_x = max_pool(relu_x)

print("\nAfter Max Pooling:")
print(max_pool_x)


Window (0,0)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Weighted Sum = 1
After Bias = -1

Window (0,1)
[[0 0 0]
 [1 0 0]
 [0 1 1]]
Weighted Sum = 0
After Bias = -2

Window (0,2)
[[0 0 0]
 [0 0 1]
 [1 1 0]]
Weighted Sum = 1
After Bias = -1

Window (0,3)
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Weighted Sum = 3
After Bias = 1

Window (1,0)
[[0 1 0]
 [0 0 1]
 [0 0 1]]
Weighted Sum = 0
After Bias = -2

Window (1,1)
[[1 0 0]
 [0 1 1]
 [0 1 1]]
Weighted Sum = 1
After Bias = -1

Window (1,2)
[[0 0 1]
 [1 1 0]
 [1 1 0]]
Weighted Sum = 3
After Bias = 1

Window (1,3)
[[0 1 0]
 [1 0 0]
 [1 0 0]]
Weighted Sum = 1
After Bias = -1

Window (2,0)
[[0 0 1]
 [0 0 1]
 [0 1 0]]
Weighted Sum = 1
After Bias = -1

Window (2,1)
[[0 1 1]
 [0 1 1]
 [1 0 0]]
Weighted Sum = 3
After Bias = 1

Window (2,2)
[[1 1 0]
 [1 1 0]
 [0 0 1]]
Weighted Sum = 1
After Bias = -1

Window (2,3)
[[1 0 0]
 [1 0 0]
 [0 1 0]]
Weighted Sum = 0
After Bias = -2

Window (3,0)
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Weighted Sum = 3
After Bias = 1

Window (3,1)
[[0 1 1]
 [1 0 

In [6]:
# Flatten the pooled maps - this is what gets fed to the dense layer
X = np.array([
    max_pool_o.flatten(),
    max_pool_x.flatten()
], dtype=float)

y = np.array([0, 1])   # 0 = O, 1 = X

print("Features:")
print(X)
print("\nLabels:", y)

Features:
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]]

Labels: [0 1]


In [11]:
# Dense layer: one neuron, sigmoid(w . features + b) -> probability the image is an X
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


rng = np.random.default_rng(0)
w = rng.normal(0, 0.5, size=X.shape[1])
b = 0.0

lr = 0.5
epochs = 300

for epoch in range(epochs):
    pred = sigmoid(X @ w + b)

    loss = -np.mean(y * np.log(pred) + (1 - y) * np.log(1 - pred))

    # gradient of binary cross entropy
    error = pred - y
    w -= lr * (X.T @ error) / len(y)
    b -= lr * np.mean(error)

    if epoch % 50 == 0:
        print(f"epoch {epoch:3d}   loss = {loss:.4f}")

print("\nTrained weights:", np.round(w, 3))
print("Trained bias:", round(b, 3))

epoch   0   loss = 0.6633
epoch  50   loss = 0.0415
epoch 100   loss = 0.0206
epoch 150   loss = 0.0136
epoch 200   loss = 0.0102
epoch 250   loss = 0.0081

Trained weights: [-2.445  2.349  2.735 -2.455]
Trained bias: -0.092


In [ ]:
# Inference: run the same pipeline, but with the weights we just trained
def predict(image, threshold=0.5):
    feature_map = convolve(image, kernel, bias, verbose=False)
    relu = np.maximum(0, feature_map)
    pooled = max_pool(relu, verbose=False)

    features = pooled.flatten().astype(float)

    # dense layer with the trained w and b
    prob = sigmoid(features @ w + b)
    label = "X" if prob >= threshold else "O"

    return label, prob, features


for name, image in [("image_o", image_o), ("image_x", image_x)]:
    label, prob, features = predict(image)
    print(f"{name}: features = {features}  P(X) = {prob:.4f}  -> predicted {label}")

In [ ]:
# An image the network never saw during training - a thicker, sloppier X
image_new = np.array([
    [1, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 1],
    [1, 0, 0, 0, 1, 1]
])

label, prob, features = predict(image_new)

print(image_new)
print("\nfeatures =", features)
print(f"P(X) = {prob:.4f}  ->  predicted {label}")

In [ ]:
# Build a noisy test set: 10 X's and 10 O's, each with a few pixels randomly flipped
def add_noise(image, n_flips, rng):
    noisy = image.copy()
    flat_idx = rng.choice(image.size, size=n_flips, replace=False)
    rows, cols = np.unravel_index(flat_idx, image.shape)
    noisy[rows, cols] = 1 - noisy[rows, cols]   # flip 0 <-> 1
    return noisy


test_rng = np.random.default_rng(42)
n_flips = 3

test_set = []
for _ in range(10):
    test_set.append((add_noise(image_o, n_flips, test_rng), 0))   # 0 = O
for _ in range(10):
    test_set.append((add_noise(image_x, n_flips, test_rng), 1))   # 1 = X

print(f"Test set: {len(test_set)} images, {n_flips} pixels flipped each\n")

In [ ]:
# Score every test image and report accuracy
names = {0: "O", 1: "X"}
correct = 0

print(f"{'#':>3}  {'true':>4}  {'pred':>4}  {'P(X)':>7}  {'features':<16}")
print("-" * 45)

for i, (image, true_label) in enumerate(test_set):
    label, prob, features = predict(image)
    is_correct = (label == names[true_label])
    correct += is_correct

    mark = "" if is_correct else "  <-- wrong"
    print(f"{i:>3}  {names[true_label]:>4}  {label:>4}  {prob:>7.4f}  {str(features):<16}{mark}")

accuracy = correct / len(test_set)
print(f"\nAccuracy: {correct}/{len(test_set)} = {accuracy:.0%}")